import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const root = process.cwd();
const localConfigPath = path.join(root, "config", "supabase.projects.local.json");
const exampleConfigPath = path.join(root, "config", "supabase.projects.example.json");
const mcpPath = path.join(root, ".mcp.json");
const codexDir = path.join(root, ".codex");
const codexConfigPath = path.join(codexDir, "config.toml");

function usage() {
  console.log(`Usage:
  npm run supabase:target
  npm run supabase:target:list
  npm run supabase:target:set -- <profile>
  npm run supabase:target:add -- <profile> <project-ref> [display-name]
  npm run supabase:mcp:write
`);
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function writeJson(filePath, value) {
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

function loadConfig() {
  if (!fs.existsSync(localConfigPath)) {
    if (!fs.existsSync(exampleConfigPath)) {
      throw new Error("Missing config/supabase.projects.local.json and example fallback.");
    }

    fs.mkdirSync(path.dirname(localConfigPath), { recursive: true });
    fs.copyFileSync(exampleConfigPath, localConfigPath);
  }

  const config = readJson(localConfigPath);

  if (!config || typeof config !== "object" || !config.profiles || typeof config.profiles !== "object") {
    throw new Error("Invalid Supabase projects config.");
  }

  return config;
}

function getActiveProfile(config) {
  const active = String(config.active || "");
  const profile = config.profiles[active];

  if (!active || !profile) {
    throw new Error(`Active Supabase profile '${active}' was not found.`);
  }

  if (!profile.projectRef) {
    throw new Error(`Supabase profile '${active}' is missing projectRef.`);
  }

  return { key: active, profile };
}

function mcpUrl(projectRef) {
  const params = new URLSearchParams({
    project_ref: projectRef,
    features: "database,docs",
  });

  return `https://mcp.supabase.com/mcp?${params.toString()}`;
}

function writeMcpFiles(config) {
  const { key, profile } = getActiveProfile(config);
  const url = mcpUrl(profile.projectRef);

  writeJson(mcpPath, {
    mcpServers: {
      supabase: {
        type: "http",
        url,
      },
    },
  });

  fs.mkdirSync(codexDir, { recursive: true });
  fs.writeFileSync(
    codexConfigPath,
    [
      "# Generated by scripts/supabase-target.mjs.",
      "# Do not commit this file; switch targets through config/supabase.projects.local.json.",
      "[mcp_servers.supabase]",
      `url = "${url}"`,
      "",
    ].join("\n")
  );

  console.log(`Supabase target: ${key} (${profile.projectRef})`);
  console.log(`Wrote ${path.relative(root, mcpPath)} and ${path.relative(root, codexConfigPath)}.`);
}

function listProfiles(config) {
  const rows = Object.entries(config.profiles).map(([key, profile]) => ({
    active: key === config.active ? "*" : " ",
    profile: key,
    projectRef: profile.projectRef,
    name: profile.name || "",
    organization: profile.organizationSlug || "",
    region: profile.region || "",
  }));

  console.table(rows);
}

function setProfile(config, profileName) {
  if (!profileName || !config.profiles[profileName]) {
    throw new Error(`Unknown Supabase profile '${profileName || ""}'.`);
  }

  config.active = profileName;
  writeJson(localConfigPath, config);
  writeMcpFiles(config);
}

function addProfile(config, [profileName, projectRef, ...displayNameParts]) {
  if (!profileName || !projectRef) {
    throw new Error("Add requires <profile> and <project-ref>.");
  }

  config.profiles[profileName] = {
    projectRef,
    name: displayNameParts.join(" ") || profileName,
  };
  config.active = profileName;
  writeJson(localConfigPath, config);
  writeMcpFiles(config);
}

function main() {
  const [command = "current", ...args] = process.argv.slice(2);
  const config = loadConfig();

  switch (command) {
    case "current": {
      const { key, profile } = getActiveProfile(config);
      console.log(`Supabase target: ${key} (${profile.projectRef})`);
      break;
    }
    case "list":
      listProfiles(config);
      break;
    case "set":
      setProfile(config, args[0]);
      break;
    case "add":
      addProfile(config, args);
      break;
    case "write":
      writeMcpFiles(config);
      break;
    case "help":
    case "--help":
    case "-h":
      usage();
      break;
    default:
      throw new Error(`Unknown command '${command}'.`);
  }
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  usage();
  process.exit(1);
}
